# Importing libraries

In [30]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn
import warnings
warnings.filterwarnings('ignore')

In [31]:
df=pd.read_csv('df_final_data.csv')

In [32]:
df.head()

Unnamed: 0  Number of Stars  \
0           0                1   
1           1                5   
2           2                5   
3           3                1   
4           4                1   

                                         Full Review  
0                           Battery problam no bakap  
1  very very best product and combo pack .super s...  
2  superrrrrrr mobiles awesome i kall you now its...  
3  key quality not good type 9 or input tuch # so...  
4       Not nice in battery switch off any time to s

In [33]:
df.shape

(20370, 3)

In [34]:
df['Number of Stars'].value_counts()

5    11920
4     4124
1     2227
3     1744
2      355
Name: Number of Stars, dtype: int64

In [35]:
df.columns

Index(['Unnamed: 0', 'Number of Stars', 'Full Review'], dtype='object')

In [36]:
import re
import string

# Data Preprocessing

In [37]:
#to clean the data by lowering the text,removing unnecessary punctuations,numbers/digits etc


def text_clean_1(text):
    text=text.lower()
    text=re.sub('\[.*?#]','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\w*\d\w*','',text)
    return text

In [38]:
cleaned1=lambda x:text_clean_1(x)

In [39]:
df['cleaned_FullReview']=pd.DataFrame(df['Full Review'].apply(cleaned1))

In [40]:
df.head(10)

Unnamed: 0  Number of Stars  \
0           0                1   
1           1                5   
2           2                5   
3           3                1   
4           4                1   
5           5                5   
6           6                1   
7           7                4   
8           8                4   
9           9                3   

                                         Full Review  \
0                           Battery problam no bakap   
1  very very best product and combo pack .super s...   
2  superrrrrrr mobiles awesome i kall you now its...   
3  key quality not good type 9 or input tuch # so...   
4       Not nice in battery switch off any time to s   
5                                       nice product   
6              Not good battery\nAnd no good speaker   
7                                               good   
8             Great Product. Roughly use verry well.   
9  Phone is good but button is coming out fevikwi...   

                                  cleaned_FullReview  
0                           battery problam no bakap  
1  very very best product and combo pack super sa...  
2  superrrrrrr mobiles awesome i kall you now its...  
3  key quality not good type  or input tuch  so b...  
4       not nice in battery switch off any time to s  
5                                       nice product  
6              not good battery\nand no good speaker  
7                                               good  
8               great product roughly use verry well  
9  phone is good but button is coming out fevikwi...

In [41]:
df.tail(20)

Unnamed: 0  Number of Stars  \
20350        5150                4   
20351        5151                4   
20352        5152                3   
20353        5153                5   
20354        5154                3   
20355        5155                4   
20356        5156                5   
20357        5157                4   
20358        5158                5   
20359        5159                5   
20360        5160                5   
20361        5161                4   
20362        5162                5   
20363        5163                5   
20364        5164                3   
20365        5165                5   
20366        5166                5   
20367        5167                5   
20368        5168                4   
20369        5169                5   

                                             Full Review  \
20350  Very good product everything is fine camera is...   
20351  Hi guys I here give u a complete review of thi...   
20352  Based on the usage for about 3 weeks, I am wri...   
20353  Love this phone😍😍😍 I bought this for my maa as...   
20354  Good phone. Budget friendly.\nBest in this bud...   
20355  Nice product fits in your budget segment.\n1) ...   
20356  Camera- Average but works fine. Back camera is...   
20357  Perfect phone\n1. Amezing camera\n2. Good perf...   
20358  Good quality of screen. Camera is average. Bat...   
20359  Best mobile in this price range. Camera would ...   
20360  Thankyou Redmi,\n\nFeeling Lucky to buy this p...   
20361  Good mobile ...I loved it and Thank you flipka...   
20362  It is an good phone ever i see, but it have on...   
20363  Nice very super product and nice performance\n...   
20364  Writing this review after 4 months of purchase...   
20365  To be completely honest this is not the best p...   
20366  Mi 9i is good no loss it is very good mobile a...   
20367  Nice mobile, good battery backup, camera satis...   
20368  I've bought this for my parents, overall phone...   
20369  Very good mobile. I love thish phone. Really g...   

                                      cleaned_FullReview  
20350  very good product everything is fine camera is...  
20351  hi guys i here give u a complete review of thi...  
20352  based on the usage for about  weeks i am writi...  
20353  love this phone😍😍😍 i bought this for my maa as...  
20354  good phone budget friendly\nbest in this budge...  
20355  nice product fits in your budget segment\n bat...  
20356  camera average but works fine back camera is g...  
20357  perfect phone\n amezing camera\n good performa...  
20358  good quality of screen camera is average batte...  
20359  best mobile in this price range camera would b...  
20360  thankyou redmi\n\nfeeling lucky to buy this pr...  
20361  good mobile i loved it and thank you flipkart ...  
20362  it is an good phone ever i see but it have onl...  
20363  nice very super product and nice performance\n...  
20364  writing this review after  months of purchase ...  
20365  to be completely honest this is not the best p...  
20366  mi  is good no loss it is very good mobile any...  
20367  nice mobile good battery backup camera satisfa...  
20368  ive bought this for my parents overall phone i...  
20369  very good mobile i love thish phone really goo...

First round of cleaning removed the punctuations, extra spaces,etc.However we could see some emojis which will be removed in the next phase

In [44]:
!pip install emoji
import emoji

  Created wheel for emoji: filename=emoji-1.4.2-py3-none-any.whl size=186457 sha256=78c4272651b9f8bdcc2aecaeaaf75e036ccc101d7f8d6ddc070fcb633f184cd4
  Stored in directory: c:\users\a\appdata\local\pip\cache\wheels\71\4d\3c\cada364d4ea0026deee7208dee1e61bcebd20aa2ae5dc154ba
Successfully built emoji


# Removing Emojis

In [45]:
def text_clean_2(text):
    text=re.sub('\n','',text)
    text=re.sub(emoji.get_emoji_regexp(),r'',text)
    return text
cleaned2=lambda x:text_clean_2(x)

df['cleaned_review_final']=pd.DataFrame(df['cleaned_FullReview'].apply(cleaned2))

In [46]:
df 

Unnamed: 0  Number of Stars  \
0               0                1   
1               1                5   
2               2                5   
3               3                1   
4               4                1   
...           ...              ...   
20365        5165                5   
20366        5166                5   
20367        5167                5   
20368        5168                4   
20369        5169                5   

                                             Full Review  \
0                               Battery problam no bakap   
1      very very best product and combo pack .super s...   
2      superrrrrrr mobiles awesome i kall you now its...   
3      key quality not good type 9 or input tuch # so...   
4           Not nice in battery switch off any time to s   
...                                                  ...   
20365  To be completely honest this is not the best p...   
20366  Mi 9i is good no loss it is very good mobile a...   
20367  Nice mobile, good battery backup, camera satis...   
20368  I've bought this for my parents, overall phone...   
20369  Very good mobile. I love thish phone. Really g...   

                                      cleaned_FullReview  \
0                               battery problam no bakap   
1      very very best product and combo pack super sa...   
2      superrrrrrr mobiles awesome i kall you now its...   
3      key quality not good type  or input tuch  so b...   
4           not nice in battery switch off any time to s   
...                                                  ...   
20365  to be completely honest this is not the best p...   
20366  mi  is good no loss it is very good mobile any...   
20367  nice mobile good battery backup camera satisfa...   
20368  ive bought this for my parents overall phone i...   
20369  very good mobile i love thish phone really goo...   

                                    cleaned_review_final  
0                               battery problam no bakap  
1      very very best product and combo pack super sa...  
2      superrrrrrr mobiles awesome i kall you now its...  
3      key quality not good type  or input tuch  so b...  
4           not nice in battery switch off any time to s  
...                                                  ...  
20365  to be completely honest this is not the best p...  
20366  mi  is good no loss it is very good mobile any...  
20367  nice mobile good battery backup camera satisfa...  
20368  ive bought this for my parents overall phone i...  
20369  very good mobile i love thish phone really goo...  

[20370 rows x 5 columns]

In [48]:
df.tail(20)

Unnamed: 0  Number of Stars  \
20350        5150                4   
20351        5151                4   
20352        5152                3   
20353        5153                5   
20354        5154                3   
20355        5155                4   
20356        5156                5   
20357        5157                4   
20358        5158                5   
20359        5159                5   
20360        5160                5   
20361        5161                4   
20362        5162                5   
20363        5163                5   
20364        5164                3   
20365        5165                5   
20366        5166                5   
20367        5167                5   
20368        5168                4   
20369        5169                5   

                                             Full Review  \
20350  Very good product everything is fine camera is...   
20351  Hi guys I here give u a complete review of thi...   
20352  Based on the usage for about 3 weeks, I am wri...   
20353  Love this phone😍😍😍 I bought this for my maa as...   
20354  Good phone. Budget friendly.\nBest in this bud...   
20355  Nice product fits in your budget segment.\n1) ...   
20356  Camera- Average but works fine. Back camera is...   
20357  Perfect phone\n1. Amezing camera\n2. Good perf...   
20358  Good quality of screen. Camera is average. Bat...   
20359  Best mobile in this price range. Camera would ...   
20360  Thankyou Redmi,\n\nFeeling Lucky to buy this p...   
20361  Good mobile ...I loved it and Thank you flipka...   
20362  It is an good phone ever i see, but it have on...   
20363  Nice very super product and nice performance\n...   
20364  Writing this review after 4 months of purchase...   
20365  To be completely honest this is not the best p...   
20366  Mi 9i is good no loss it is very good mobile a...   
20367  Nice mobile, good battery backup, camera satis...   
20368  I've bought this for my parents, overall phone...   
20369  Very good mobile. I love thish phone. Really g...   

                                      cleaned_FullReview  \
20350  very good product everything is fine camera is...   
20351  hi guys i here give u a complete review of thi...   
20352  based on the usage for about  weeks i am writi...   
20353  love this phone😍😍😍 i bought this for my maa as...   
20354  good phone budget friendly\nbest in this budge...   
20355  nice product fits in your budget segment\n bat...   
20356  camera average but works fine back camera is g...   
20357  perfect phone\n amezing camera\n good performa...   
20358  good quality of screen camera is average batte...   
20359  best mobile in this price range camera would b...   
20360  thankyou redmi\n\nfeeling lucky to buy this pr...   
20361  good mobile i loved it and thank you flipkart ...   
20362  it is an good phone ever i see but it have onl...   
20363  nice very super product and nice performance\n...   
20364  writing this review after  months of purchase ...   
20365  to be completely honest this is not the best p...   
20366  mi  is good no loss it is very good mobile any...   
20367  nice mobile good battery backup camera satisfa...   
20368  ive bought this for my parents overall phone i...   
20369  very good mobile i love thish phone really goo...   

                                    cleaned_review_final  
20350  very good product everything is fine camera is...  
20351  hi guys i here give u a complete review of thi...  
20352  based on the usage for about  weeks i am writi...  
20353  love this phone i bought this for my maa as a ...  
20354  good phone budget friendlybest in this budgetd...  
20355  nice product fits in your budget segment batte...  
20356  camera average but works fine back camera is g...  
20357  perfect phone amezing camera good performance ...  
20358  good quality of screen camera is average batte...  
20359  best mobile in this price range camera would b...  
20360  thankyou redmifeeling lucky to

# Model building

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import LinearSVC

In [ ]:
#splitting of data

In [51]:
x=df['cleaned_review_final']
y=df['Number of Stars']

In [53]:
x.head()

0                             battery problam no bakap
1    very very best product and combo pack super sa...
2    superrrrrrr mobiles awesome i kall you now its...
3    key quality not good type  or input tuch  so b...
4         not nice in battery switch off any time to s
Name: cleaned_review_final, dtype: object

In [54]:
y.head()

0    1
1    5
2    5
3    1
4    1
Name: Number of Stars, dtype: int64

In [55]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

# Creating Pipeline

In [59]:
tvec=TfidfVectorizer()
clf2=LinearSVC()
from sklearn.pipeline import Pipeline

In [61]:
model=Pipeline([('vectorizer',tvec),('classifier',clf2)])
model.fit(x_train,y_train)

pred=model.predict(x_test)
print(confusion_matrix(pred,y_test))
print(accuracy_score(pred,y_test))

[[ 441    0    3    0    0]
 [   0   59    0    0    0]
 [   0    0  340    0    0]
 [   0    0    0  755    0]
 [   8    0   23   55 2390]]
0.978154148257241


accuracy score was found to be 97.8 percent

In [64]:
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           1       0.98      0.99      0.99       444
           2       1.00      1.00      1.00        59
           3       0.93      1.00      0.96       340
           4       0.93      1.00      0.96       755
           5       1.00      0.97      0.98      2476

    accuracy                           0.98      4074
   macro avg       0.97      0.99      0.98      4074
weighted avg       0.98      0.98      0.98      4074



# Testing the model on a new review

In [66]:
#testing the model on new review
example=['pathetic product']
result=model.predict(example)
print(result)

[1]


In [67]:
example2=['delighted with the product']
result=model.predict(example2)
print(result)

[5]


In [68]:
example3=['average product']
result=model.predict(example3)
print(result)

[3]


# saving the model

In [69]:
import joblib

In [70]:
filename='ratingmodel.pkl'

In [71]:
joblib.dump(model,'ratingmodel.pkl')

['ratingmodel.pkl']